image: node:latest

cache:
  paths:
  - node_modules/

job:
  script:
  - apt-get update -qy
  - apt-get install -y ruby ruby-dev rubygems-integration
  - npm install
  - gem install --no-rdoc --no-ri dpl
  - dpl --provider=heroku --app=muzyk-discord --api-key=ODQzNzkwMjAyMDY1MTI1Mzg2.YKI-3Q.-D47yMIP6SHO85hvhwE3jhKkATw
# change app name and api key if necessary
